/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "CutThroughTheTraffic": {
      "type": "sst.aws.SvelteKit"
      "url": string
    }
    "GEMINI_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "POSTGRES_CONNECTION_STRING": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRAVA_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRAVA_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRAVA_REFRESH_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StravaTokensTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "TELEGRAM_BOT_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TelegramUsersTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}